Add bookings
pkingsbl/java-shareit pull request #2
Opened 2023-02-24 18:01 UTC by pkingsbl

2023-02-25 15:38 UTC, Fleaman777 requested changes

2023-02-25 15:38 UTC, Fleaman777 commented on pom.xml
> +		<puppycrawl.version>10.3</puppycrawl.version>
хорошая идея вынести версии в одно место, так удобней будет ими управлять

2023-02-25 15:38 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/mapper/CommentMapper.java
> +    }
хороший метод для того что бы сделать его через стрим

2023-02-25 15:38 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        }
большая вложенность методов может плозо восприниматься, 
что бы упростить, какую-то часть можно вынести в локальные переменные, с подходящим именем

применимо ко всем похожим местам

2023-02-26 13:56 UTC, pkingsbl commented
Ошибки в новых тестах 
    pm.expect(jsonData.nextBooking.id, '"nextBooking.id" must be "1"').to.eql(4);
    pm.expect(jsonData.nextBooking.bookerId, '"nextBooking.bookerId" must be "1"').to.eql(5);
    pm.expect(jsonData[0].nextBooking.id, '"nextBooking.id" must be "1"').to.eql(4);
итд

2023-02-28 18:42 UTC, Fleaman777 approved these changes

2023-02-28 19:28 UTC, merged