added item request
pkingsbl/java-shareit pull request #3
Opened 2023-03-06 21:01 UTC by pkingsbl

2023-03-12 19:23 UTC, Fleaman777 requested changes

2023-03-12 19:23 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        return itemRequest.get();
у класса Optional есть хорошие методы например  orElseThrow, 
который позволит немного сократить метод  chackItemReq,

аналагично в других подобных местах

2023-03-12 19:23 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/request/service/ItemRequestServiceImpl.java
> +        itemRequestDto.setItems(mapToItemDto(itemRepository.findAllByRequestId(itemRequestDto.getId())));
большая вложенность в качестве аргумента метода, немного ухудшает восприятие, 
лучше было бы немного разложить и какие-то результаты перенести в локальные переменные

2023-03-12 19:23 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    BookingService bookingService;
в тестах тоже хорошо придерживаться принципа инкапсуляции и делать поля private

2023-03-12 19:23 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +            .end(LocalDate.now().atStartOfDay().plusDays(4).plusSeconds(1))
LocalDate.now() - можно было бы вынести в отдельную перменную

2023-03-12 19:23 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    void findById() throws Exception {
названия тест методов отличные, но есть что поправить

тестовые методы лучше называть немного по другому, чем методы самого приложения.
будет проще ориентироваться, если придется полнотекстово искать название метода во всем коду

самое простое другое название в начале метода добавить test,
еще лучше добавлять условние при котором выполняется тест, т.е. findByIdIf...

2023-03-12 19:23 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/repository/BookingRepositoryTest.java
> +        assertTrue(bookings.contains(booking));
эти несколько ассертов выглядят так же как и в других тест методах, 
что бы было меньше дублирования, их можно вынести в отдельный метод,

2023-03-12 19:23 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/request/service/ItemRequestServiceImplTest.java
> +    private final UserRepository userRepository = mock(UserRepository.class);
вместо использования статического метода mock(UserRepository.class, можно использовать аннотацию @Mock 
а что бы явно не создавать сервис через конструктор new ItemRequestServiceImpl(userRepository, itemRepository, itemRequestRepository);, можно использовать @InjectMock

как результат
сократится количество кода, улучшится читаемость

2023-03-14 16:56 UTC, Fleaman777 approved these changes

2023-03-14 16:56 UTC, Fleaman777 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        return userRepository.findById(userId).orElseThrow(() -> new NotFoundException("Пользователь не найден"));
вот это совсем другой вид, супер)

2023-03-14 16:56 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +    void testApproveWithoutRequestParam() throws Exception {
отлично, мне нравится

2023-03-14 16:56 UTC, Fleaman777 commented on src/test/java/ru/practicum/shareit/item/service/ItemServiceImplTest.java
> +    @MockBean
эта аннотация тоже подходит, но я упомянал немного другую (@Mock)
эти 2 аннотации +- одинаковые, но есть и отличия, можешь для обшего развития посмотреть, чем они отличаются,

если что, исправлять не обязательно)

2023-03-14 18:25 UTC, pkingsbl commented on src/test/java/ru/practicum/shareit/item/service/ItemServiceImplTest.java
> +    @MockBean
c @mock не походили тесты, не разобралась почему. Не работали заглуши репозитория на методы с возвращаемым значением

2023-03-23 22:27 UTC, merged